// this carousel assumes all elements inside have the same width

module.exports = {
  addCarousel
}

function addCarousel(galleryId, prevId, nextId) {
  var galleryNode = document.getElementById(galleryId)
  var prevNode = document.getElementById(prevId)
  var nextNode = document.getElementById(nextId)

  if(galleryNode === null || prevNode === null || nextNode === null) {
    console.warn('Missing element(s) required for carousel')
    return
  }

  let item = galleryNode.firstChild
  while (item.nodeName === '#text') item = item.nextSibling // skip text nodes generated by source whitespace
  let itemSibling = item.nextSibling
  while (itemSibling.nodeName === '#text') itemSibling = itemSibling.nextSibling
  var step = itemSibling.getBoundingClientRect().x - item.getBoundingClientRect().x
  console.log(step)

  nextNode.addEventListener('click', () => {
    console.log('clicked')
    galleryNode.scrollBy({
      top: 0,
      left: step,
      behavior: 'smooth'
    })
  })

  prevNode.addEventListener('click', () => {
    console.log('clicked')
    galleryNode.scrollBy({
      top: 0,
      left: -step,
      behavior: 'smooth'
    })
  })
}